[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.2.1"
sdl2 = "0.37.0"
rand = "0.8.4"
bytes = "1.2.1"